### ISSUE TITLE
[BUG] Reduced download speed

### ISSUE THREAD

**Issue by Tartilla-TAIGO** [Corona-Studio/ProjBobcat#172]
After the DownloadHelper update, the download speed dropped from 250+ mb/s to 100-200 kb/s. 

The download speed was approximately in February-January of this year before the update:
stdout: [11.06.2025 10:19:02]: (Stage: Vanilla ResourceCompleter Installer) <Asset> Success 916a6ee50492987b33c58909bd0f86c275d49cfd [248.988 Mb / s] 92.12639212639213%

stdout: [11.06.2025 10:19:02]: (Stage: Vanilla ResourceCompleter Installer) <Asset> Success ef1fea92382e98356a8c39e3c99b91d72d55f342 [257.473 Mb / s] 92.15229215229215%

After update: 
2025-06-11 16:23:46.3812|INFO|<Asset><Retry - 0> Success 2bbb5670f166a6c0898e83a36d6ddf0b70a4c3f0 [3,4 Kb / s]
2025-06-11 16:23:46.4495|INFO|<Asset><Retry - 0> Success 79948a332ee6c72d38fe54291118120c144b2c8b [3,1 Kb / s]

**Comment by Tartilla-TAIGO** [comment]
This method uses the DefaultResourceResolver, so downloading all files is very slow.

**Comment by Tartilla-TAIGO** [comment]
If I understood you correctly, you wrote that you changed the download speed calculation and therefore the speed seems slow, but that's not the point here. Now the library spends about 6 minutes downloading vanilla resource packages, and if you upgrade to an older version, it downloads the same resources in about 30 seconds.

**Comment by laolarou726** [comment]
> For some reason, the second construct that was added in the new version runs 6 times slower than the for loop and if I use old downloadhelper.
> 
> 1). for (var i = 0; i <= trials; i++) downloadFile.RetryCount = i
> 
> 2). while (downloadFile.RetryCount++ < trials)

Could you please try the latest commit? I believe the issue was resolved!

**Comment by Tartilla-TAIGO** [comment]
It's gotten a little better, but it's still not the same download speeds that it used to be. Before your changes, it took about 6 minutes, now it takes about 4 minutes, although previously it took about 40 seconds. I wrote a hybrid version (I changed the old DownloadHelper to new variables, as well as DefaultResourcesResolver to the old loader) - this allowed me to get closer to the old download speed of about 50 seconds. I'll send a link to it in a few minutes.

**Comment by laolarou726** [comment]
> It's gotten a little better, but it's still not the same download speeds that it used to be. Before your changes, it took about 6 minutes, now it takes about 4 minutes, although previously it took about 40 seconds. I wrote a hybrid version (I changed the old DownloadHelper to new variables, as well as DefaultResourcesResolver to the old loader) - this allowed me to get closer to the old download speed of about 50 seconds. I'll send a link to it in a few minutes.

Have you tried to increase DownloadParts and DownloadThread?

**Comment by Tartilla-TAIGO** [comment]
https://github.com/Tartilla-TAIGO/ProjBobcat
Here is a link to the modified resource, there are small tests there - I tested the automatic blocking of the domain if it is unavailable to switch to a backup resource, but this does not affect performance in any way.

**Comment by Tartilla-TAIGO** [comment]
Yes, I tried before, this is the first thing that came to my mind and I changed the parameters, but it did not give a big increase in speed. I currently have 48 download threads. I used the same number of threads to test your loader and my own.

**Comment by laolarou726** [comment]
I believe this code will cause a race condition and cause the checker to ignore some of the files:

```
var checkAction = new ActionBlock<IResourceInfoResolver>(async resolver =>
    {
        resolver.GameResourceInfoResolveEvent += FireResolveEvent;

        await Parallel.ForEachAsync(
            resolver.ResolveResourceAsync(basePath, checkLocalFiles, resolvedGame),
            new ParallelOptions { MaxDegreeOfParallelism = MaxDegreeOfParallelism },
            ReceiveGameResourceTask);

        return;

        void FireResolveEvent(object? sender, GameResourceInfoResolveEventArgs e)
        {
            if (!downloadBag.IsEmpty)
            {
                resolver.GameResourceInfoResolveEvent -= FireResolveEvent;
                return;
            }

            OnResolveComplete(sender, e);
        }
    }, new ExecutionDataflowBlockOptions
    {
        BoundedCapacity = MaxDegreeOfParallelism,
        MaxDegreeOfParallelism = MaxDegreeOfParallelism
    });

    foreach (var r in ResourceInfoResolvers!)
        await checkAction.SendAsync(r);
    checkAction.Complete();
    await checkAction.Completion;
    if (downloadBag.IsEmpty)
        return new TaskResult<ResourceCompleterCheckResult?>(
            TaskResultStatus.Success,
            value: new ResourceCompleterCheckResult { FailedFiles = [], IsLibDownloadFailed = false });
    var downloads = downloadBag.ToArray();
    Random.Shared.Shuffle(downloads);
    await DownloadHelper.AdvancedDownloadListFile(downloads, downloadSettings);
```

**Comment by laolarou726** [comment]
> Yes, I tried before, this is the first thing that came to my mind and I changed the parameters, but it did not give a big increase in speed. I currently have 48 download threads. I used the same number of threads to test your loader and my own.

You can try assigning 16 download parts and 128 download threads. In my test, for 1.21.5, the completion will finish in 1 minute

**Comment by Tartilla-TAIGO** [comment]
I copied it from one of the previous versions of the library, according to the debug data, it receives this number of files

**Comment by Tartilla-TAIGO** [comment]
I set the settings that you specified and everything was installed in 3 minutes and 40 seconds. For minecraft 1.20.4

**Comment by laolarou726** [comment]
> I copied it from one of the previous versions of the library, according to the debug data, it receives this number of files

I just tried again, it took 40 seconds to check and download all the assets and libraries for 1.21.5 game. My network is 500 mbps

**Comment by Tartilla-TAIGO** [comment]
<img width="576" alt="Image" src="https://github.com/user-attachments/assets/73e3395a-59d3-4c53-a833-3528d89770c7" />

<img width="1200" alt="Image" src="https://github.com/user-attachments/assets/b2657be4-eefd-4dc5-ad10-afaec41eaf5f" />

<img width="653" alt="Image" src="https://github.com/user-attachments/assets/749068bd-eb7f-498a-8d98-ee28c6cf8206" />

**Comment by laolarou726** [comment]
> <img alt="Image" width="576" src="https://private-user-images.githubusercontent.com/126141594/454693334-73e3395a-59d3-4c53-a833-3528d89770c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDk3OTAxMzMsIm5iZiI6MTc0OTc4OTgzMywicGF0aCI6Ii8xMjYxNDE1OTQvNDU0NjkzMzM0LTczZTMzOTVhLTU5ZDMtNGM1My1hODMzLTM1MjhkODk3NzBjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDYxM1QwNDQzNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGZhMzNiNGNkZGYxN2QyNzNlYjUzY2VlODliMWE3Nzk0MjZhZGU2OTQxZjk4ZTk2ZTc0NDJjMDJhNGIzNzFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DpuUWqFewJaGJyEPXzLvcRnIInjzDt_wI42uVdqMS6E"> <img alt="Image" width="1200" src="https://private-user-images.githubusercontent.com/126141594/454693398-b2657be4-eefd-4dc5-ad10-afaec41eaf5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDk3OTAxMzMsIm5iZiI6MTc0OTc4OTgzMywicGF0aCI6Ii8xMjYxNDE1OTQvNDU0NjkzMzk4LWIyNjU3YmU0LWVlZmQtNGRjNS1hZDEwLWFmYWVjNDFlYWY1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDYxM1QwNDQzNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTY3MzE1MGJiNWY4NmQ1MDM4YTdhMzhkNjQyODg5NzYzNWRkY2NjZjYyZTUwYTQ0MTc0NDA3ZDJlNWViYTRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pQLMzMlj36tLVqj-71765882CPMeyJGwzckHAsOkh30"> <img alt="Image" width="653" src="https://private-user-images.githubusercontent.com/126141594/454693525-749068bd-eb7f-498a-8d98-ee28c6cf8206.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDk3OTAxMzMsIm5iZiI6MTc0OTc4OTgzMywicGF0aCI6Ii8xMjYxNDE1OTQvNDU0NjkzNTI1LTc0OTA2OGJkLWViN2YtNDk4YS04ZDk4LWVlMjhjNmNmODIwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDYxM1QwNDQzNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmEzZDhkYjY4N2M4MWI3OTZkZmRlYjE5MzRlZGI2NzM1ZWRiNGYwM2I0ZGJhMTZkZTI0N2U0Zjc3MDk2NjczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ThyafqBwErYYQv3XZQbvT-aMc7okT14CrnyI0SXOK0c">

just pushed another commit, can you give a try?

**Comment by Tartilla-TAIGO** [comment]
The installation time remains the same

**Comment by Tartilla-TAIGO** [comment]
My test loader:

public class TestInstallFiles
{
    private static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger();

    public static async Task<bool> StartAsync()
    {
        var clientToken = new Guid("88888888-8888-8888-8888-888888888888");
        var rootPath = "/Users/semennoskov/minecraft";

        var core = new DefaultGameCore
        {
            ClientToken = clientToken,
            RootPath = rootPath,
            VersionLocator = new DefaultVersionLocator(rootPath, clientToken)
            {
                LauncherProfileParser = new DefaultLauncherProfileParser(rootPath, clientToken),
                LauncherAccountParser = new DefaultLauncherAccountParser(rootPath, clientToken)
                {
                    LauncherAccount = new LauncherAccountModel
                    {
                        MojangClientToken = string.Empty,
                    }
                }

            },

            GameLogResolver = new DefaultGameLogResolver()
        };
        
        var versionInfo = core.VersionLocator.GetGame("1.20.4");
        
        var resolvedGameVersion = core.VersionLocator.ResolveGame(
            versionInfo, 
            NativeReplacementPolicy.LegacyOnly, 
            GetJavaRuntimeInfo("/Users/semennoskov/minecraft/runtime/mac-os-arm64/java-runtime-gamma/jre.bundle/Contents/Home/bin/java"));
        
        if(resolvedGameVersion is null) return false;
        var resolvers = new List<IResourceInfoResolver>();
        var versionManifest = await GetVersionManifestAsync(ProxyUrlManager.VanillaVersionManifest);
        if (versionManifest is null)
        {
            Logger.Warn(
                "Failed to fetch Version Manifest from remote. Please check your network connection.");
            return false;
        }

        resolvers.Add(new VersionInfoResolver());
        resolvers.Add(GetAssetInfoResolver(versionManifest));
        resolvers.Add(GetLibraryInfoResolver());

        var completer = GetResourceCompleter(resolvers, 8, 128, 16, true);
        var procent = 0d;
        
        completer.DownloadFileChangedEvent += (_, args) => { procent = args.ProgressPercentage; };
        completer.DownloadFileCompletedEvent += (sender, args) =>
        {
            if (sender is not MultiSourceDownloadFile file) return;

            if (args.DownloadEventArgs.Error != null)
                Logger.Error($"Failed to download file {file.FileName}. Exception: {args.DownloadEventArgs.Error.Message}");


            var isSuccess = args.DownloadEventArgs.Success == true ? "Success" : "Failed";
            var retry = file.RetryCount == 1
                ? null
                : $"<Retry - {file.RetryCount}>";
            var fileName = file.FileName;
            var speed = DownloadHelper.AutoFormatSpeedString(args.DownloadEventArgs.AverageSpeed);
            var pD = $"<{file.FileType}>{retry} {isSuccess} {fileName} [{speed}]";
            Logger.Info($"{pD} {procent}% [{speed}]");
        };
        var result = await completer.CheckAndDownloadTaskAsync(rootPath, true,
            resolvedGameVersion);
        if (result.TaskStatus == TaskResultStatus.Error || (result.Value?.IsLibDownloadFailed ?? false))
            Logger.Error($"Failed to download assets game {resolvedGameVersion.DirName}.");
        return result.TaskStatus == TaskResultStatus.Success;
    }
    
    private static JavaRuntimeInfo? GetJavaRuntimeInfo(string? javaPath)
    {
        return javaPath is null ? null : new JavaRuntimeInfo(
            javaPath,
            SystemInfoHelper.GetOsPlatform(),
            RuntimeInformation.ProcessArchitecture,
            true, true);
    } 
    
    private static IResourceInfoResolver GetAssetInfoResolver(VersionManifest versionManifest)
    {

        return new AssetInfoResolver
        {
            AssetIndexUriRoots = ProxyUrlManager.AssetIndexUriRoots,
            AssetUriRoots = ProxyUrlManager.AssetUriRoots,
            Versions = versionManifest.Versions,
            HttpClientFactory = HttpClientFactory.Instance,
        };
    }

    private static IResourceInfoResolver GetLibraryInfoResolver()
    {
        return new LibraryInfoResolver
        {
            LibraryUriRoots = ProxyUrlManager.LibraryUriRoots,
            ForgeUriRoots = ProxyUrlManager.ForgeUriRoots,
            ForgeMavenUriRoots = ProxyUrlManager.ForgeMavenUriRoots,
            ForgeMavenOldUriRoots = ProxyUrlManager.ForgeMavenOldUriRoots,
            FabricMavenUriRoots = ProxyUrlManager.FabricMavenUriRoots,
        };
    }
    



    private static IResourceCompleter GetResourceCompleter(
        IReadOnlyList<IResourceInfoResolver> resourceInfoResolvers,
        int maxDegreeOfParallelism,
        int downloadThreads,
        int downloadParts,
        bool verifyDownloadedFiles)
    {
        return new DefaultResourceCompleter
        {
            MaxDegreeOfParallelism = maxDegreeOfParallelism,
            ResourceInfoResolvers = resourceInfoResolvers,
            TotalRetry = 3,
            CheckFile = verifyDownloadedFiles,
            DownloadParts = downloadParts,
            DownloadThread = downloadThreads,
            TimeoutPerFile = TimeSpan.FromSeconds(8),
            HttpClientFactory = HttpClientFactory.Instance,
        };
    }

    private static async Task<VersionManifest?> GetVersionManifestAsync(List<string> urls)
    {
        VersionManifest? result = null;
        var retryCount = 0;

        do
        {
            try
            {
                var url = retryCount > 0 ? urls.LastOrDefault() : urls.FirstOrDefault();
                using var req = new HttpRequestMessage(HttpMethod.Get, url);
                using var cts = new CancellationTokenSource(10000);
                using var client = new HttpClient();
                using var res = await client.SendAsync(req, cts.Token);

                result = await res.Content.ReadFromJsonAsync(
                    VersionManifestContext.Default.VersionManifest,
                    cts.Token);
            }
            catch (TaskCanceledException)
            {
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
            finally
            {
                retryCount++;
                await Task.Delay(1500 * retryCount);
            }
        } while (result == null && retryCount != 3);

        return result;
    }
}

**Comment by Tartilla-TAIGO** [comment]
Thank you
